<?php
add_action('init', function () {
	register_post_type('recipe', array(
		'labels' => array(
			'name' => 'Recipes',
			'singular_name' => 'Recipe',
			'menu_name' => 'Recipes',
			'all_items' => 'All Recipes',
			'edit_item' => 'Edit Recipe',
			'view_item' => 'View Recipe',
			'view_items' => 'View Recipes',
			'add_new_item' => 'Add New Recipe',
			'add_new' => 'Add New Recipe',
			'new_item' => 'New Recipe',
			'parent_item_colon' => 'Parent Recipe:',
			'search_items' => 'Search Recipes',
			'not_found' => 'No recipes found',
			'not_found_in_trash' => 'No recipes found in Trash',
			'archives' => 'Recipe Archives',
			'attributes' => 'Recipe Attributes',
			'insert_into_item' => 'Insert into recipe',
			'uploaded_to_this_item' => 'Uploaded to this recipe',
			'filter_items_list' => 'Filter recipes list',
			'filter_by_date' => 'Filter recipes by date',
			'items_list_navigation' => 'Recipes list navigation',
			'items_list' => 'Recipes list',
			'item_published' => 'Recipe published.',
			'item_published_privately' => 'Recipe published privately.',
			'item_reverted_to_draft' => 'Recipe reverted to draft.',
			'item_scheduled' => 'Recipe scheduled.',
			'item_updated' => 'Recipe updated.',
			'item_link' => 'Recipe Link',
			'item_link_description' => 'A link to a recipe.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-food',
		'supports' => array(
			0 => 'title',
			1 => 'custom-fields',
		),
		'delete_with_user' => false,
	));
});
